version: '3.2'

services:

  flockpocket:
    container_name: flockpocket
    image: levmason/flockpocket:latest
    command: ./docker/.start.sh
    security_opt:
      - seccomp:unconfined
    env_file:
      - ./env/flockpocket.env
    volumes:
      - ./storage:/home/flockpocket/storage/
      - ../:/opt/flockpocket/
    depends_on:
      - db
      - redis

  db:
    image: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./env/postgres.env

  redis:
    image: redis

  nginx:
    container_name: nginx
    image: nginx
    command: >
      sh -c "
      cp -f /opt/flockpocket/server/nginx/flockpocket.conf /etc/nginx/conf.d/default.conf &&
      sed -i s/{daphne_bind}/flockpocket:$${FLOCKPOCKET_DAPHNE_PORT}/g /etc/nginx/conf.d/default.conf &&
      nginx -g 'daemon off;'
      "
    ports:
      - 80:80
      - 443:443
    restart: always
    env_file:
      - ./env/flockpocket.env
    volumes:
      - ../:/opt/flockpocket/
    depends_on:
      - flockpocket

volumes:
  postgres_data:
