version: '3.2'

services:

  flockpocket:
    container_name: flockpocket
    image: levmason/flockpocket:latest
    command: ./docker/.start.sh
    security_opt:
      - seccomp:unconfined
    env_file:
      - flockpocket.env
    volumes:
      - ./storage:/home/flockpocket/storage/
      - ../:/opt/flockpocket/
    depends_on:
      - db
      - redis

  db:
    container_name: flockpocket_db
    image: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=flockpocket
    env_file:
      - flockpocket.env

  redis:
    container_name: flockpocket_redis
    image: redis

  nginx:
    container_name: flockpocket_nginx
    image: nginx
    command: >
      sh -c "
      cp -f /opt/flockpocket/server/nginx/nginx.conf /etc/nginx/conf.d/default.conf &&
      nginx -g 'daemon off;'
      "
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ../:/opt/flockpocket/
    depends_on:
      - flockpocket

volumes:
  postgres_data:
