#!/bin/sh

### BEGIN INIT INFO
# Provides:          flockpocket
# Required-Start:    $local_fs $remote_fs $network $syslog syslog-ng nginx postgresql redis-server
# Required-Stop:     $local_fs $remote_fs $network $syslog syslog-ng nginx postgresql redis-server
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: flockpocket services
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/local/bin/flockpocket
NAME=flockpocket

case "$1" in
    start|stop|restart)
	ulimit -n 65536
	$DAEMON $1
	;;
    *)
	echo "Usage: /etc/init.d/$NAME {start|stop|restart}"
	exit 1
	;;

esac

exit 0
