#!/usr/bin/env python
"""This file is automatically generated by generate_version_info
It uses the current working tree to determine the revision.
So don't edit it. :)
"""

version_info = {'branch_nick': u'python-daemon.devel',
 'build_date': '2014-08-04 15:17:39 +1000',
 'clean': None,
 'date': '2014-08-04 15:15:33 +1000',
 'revision_id': 'ben+python@benfinney.id.au-20140804051533-cg428nfiuigo0kax',
 'revno': '241'}

revisions = {}

file_revisions = {}


if __name__ == '__main__':
    print('revision: %(revno)s' % version_info)
    print('nick: %(branch_nick)s' % version_info)
    print('revision id: %(revision_id)s' % version_info)
